version: "3"
services:
  spark:
    image: jupyter/pyspark-notebook
    container_name: spark-node
    restart: always
    ports:
      - "8888:8888"
      - "4040:4040"
    # volumes:
       # - ./pyspark:/file
  elasticsearch:
    image: elasticsearch:7.5.2
    container_name: elasticsearch-node
    restart: always
    ports: 
      - "9200:9200"
    # volumes:
      # - ./elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "transport.host=127.0.0.1"
    ulimits:
      nproc: 3000
      nofile: 65536
      memlock: -1
    deploy:
      resources:
        limits:
          memory: 2g
  kibana:
    image: kibana:7.5.2
    container_name: kibana-node
    restart: always
    ports:
      - "5601:5601"

# volumes:
#    pyspark:
#        driver: local
#    elasticsearch:
#        driver: local        
